# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# DynamoDB table: idempotency
module "dynamodb_idempotency" {
  source              = "../node_modules/@j0nathan-ll0yd/cli/modules/dynamodb"
  table_name          = "idempotency"
  name_prefix         = module.core.name_prefix
  tags                = module.core.common_tags
  hash_key            = "id"
  attributes          = [{ name = "id", type = "S" }]
  table_name_override = "${module.core.name_prefix}-Idempotency"
  ttl_attribute       = "expiration"
}
