# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# --- DownloadOrchestrator ---

module "lambda_download_orchestrator" {
  source = "../../../Repositories/mantle/modules/lambda"

  function_name      = "DownloadOrchestrator"
  name_prefix        = module.core.name_prefix
  source_dir         = "${path.module}/../build/lambdas/DownloadOrchestrator"
  assume_role_policy = module.core.lambda_assume_role_policy
  xray_policy_arn    = module.core.lambda_xray_policy_arn
  region             = module.core.region
  account_id         = module.core.account_id
  environment        = var.environment
  log_retention_days = var.log_retention_days
  log_level          = var.log_level
  tags               = module.core.common_tags
  layers             = [local.adot_layer_arn]

  api_gateway_enabled = false

  environment_variables = merge(local.common_lambda_env, {
      DSQL_ROLE_NAME = local.lambda_dsql_roles["DownloadOrchestrator"].role_name
      DSQL_ENDPOINT = module.database.cluster_endpoint
      DSQL_REGION = module.core.region
      BUCKET = module.storage_files.bucket_id
      CLOUDFRONT_DOMAIN = module.storage_files.cloudfront_domain_name
      SNS_QUEUE_URL = module.queue_SendPushNotification.queue_url
      GITHUB_PERSONAL_TOKEN = var.github_personal_token
      PATH = var.path
      YTDLP_SLEEP_REQUESTS = var.ytdlp_sleep_requests
      YTDLP_SLEEP_INTERVAL = var.ytdlp_sleep_interval
      YTDLP_MAX_SLEEP_INTERVAL = var.ytdlp_max_sleep_interval
      YTDLP_BINARY_PATH = var.ytdlp_binary_path
      EVENT_BUS_NAME = local.event_bus_name
      EVENT_SOURCE = "media-downloader"
  })

    additional_policy_arns = [module.database.connect_policy_arn]

  inline_policies = {
    "S3Access" = jsonencode({
      Version = "2012-10-17"
      Statement = [{
        Effect   = "Allow"
        Action   = ["s3:AbortMultipartUpload","s3:HeadObject","s3:ListMultipartUploadParts","s3:PutObject"]
        Resource = "${module.storage_files.bucket_arn}/*"
      }]
    })
    "SQSSend_Sendpushnotification" = jsonencode({
      Version = "2012-10-17"
      Statement = [{
        Effect   = "Allow"
        Action   = "sqs:SendMessage"
        Resource = module.queue_SendPushNotification.queue_arn
      }]
    })
    "EventBridgePutEvents" = jsonencode({
      Version = "2012-10-17"
      Statement = [{
        Effect   = "Allow"
        Action   = "events:PutEvents"
        Resource = module.eventbridge.bus_arn
      }]
    })
  }
}
