# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# --- Helpers ---

module "lambda_helpers" {
  source = "../../mantle/modules/lambda"

  function_name      = "Helpers"
  name_prefix        = module.core.name_prefix
  source_dir         = "${path.module}/../build/lambdas/Helpers"
  assume_role_policy = module.core.lambda_assume_role_policy
  xray_policy_arn    = module.core.lambda_xray_policy_arn
  region             = module.core.region
  account_id         = module.core.account_id
  environment        = var.environment
  log_retention_days = var.log_retention_days
  log_level          = var.log_level
  tags               = module.core.common_tags
  layers             = [local.adot_layer_arn]

  api_gateway_enabled = false

  environment_variables = merge(local.common_lambda_env, {
      DSQL_ROLE_NAME = local.lambda_dsql_roles["Helpers"].role_name
      DSQL_ENDPOINT = module.database.cluster_endpoint
      DSQL_REGION = module.core.region
      NODE_ENV = var.node_env
      RESERVED_CLIENT_IP = var.reserved_client_ip
  })

    additional_policy_arns = [module.database.connect_policy_arn]

  inline_policies = {
    "ApiGatewayAccess" = jsonencode({
      Version = "2012-10-17"
      Statement = [{
        Effect   = "Allow"
        Action   = ["apigateway:GET"]
        Resource = "arn:aws:apigateway:*::/*"
      }]
    })
  }
}
