# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# --- LogNotifier ---

module "lambda_log_notifier" {
  source = "../node_modules/@j0nathan-ll0yd/cli/modules/lambda"

  function_name      = "LogNotifier"
  name_prefix        = module.core.name_prefix
  source_dir         = "${path.module}/../build/lambdas/LogNotifier"
  assume_role_policy = module.core.lambda_assume_role_policy
  xray_policy_arn    = module.core.lambda_xray_policy_arn
  region             = module.core.region
  account_id         = module.core.account_id
  environment        = var.environment
  log_retention_days = var.log_retention_days
  log_level          = var.log_level
  tags               = module.core.common_tags
  timeout            = 30
  memory_size        = 256
  layers             = [local.adot_layer_arn]

  api_gateway_enabled = false

  environment_variables = merge(local.common_lambda_env, {
    ALERTS_TOPIC_ARN = module.observability.sns_topic_arn
  })
}
