# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# --- DevTools ---

module "lambda_dev_tools" {
  source = "../../mantle/modules/lambda"

  function_name      = "DevTools"
  name_prefix        = module.core.name_prefix
  source_dir         = "${path.module}/../build/lambdas/DevTools"
  assume_role_policy = module.core.lambda_assume_role_policy
  xray_policy_arn    = module.core.lambda_xray_policy_arn
  region             = module.core.region
  account_id         = module.core.account_id
  environment        = var.environment
  log_retention_days = var.log_retention_days
  log_level          = var.log_level
  tags               = module.core.common_tags
  timeout            = 30
  memory_size        = 512
  layers             = [local.adot_layer_arn]

  function_url_enabled   = true
  function_url_auth_type = "NONE"

  api_gateway_enabled = false

  environment_variables = merge(local.common_lambda_env, {
      DSQL_ROLE_NAME = local.lambda_dsql_roles["DevTools"].role_name
      DSQL_ENDPOINT = module.database.cluster_endpoint
      DSQL_REGION = module.core.region
      DATA_BUCKET = var.data_bucket
  })

    additional_policy_arns = [module.database.connect_policy_arn]
}
