# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

terraform {
  required_version = ">= 1.11.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.0"
    }
    sops = {
      source  = "carlpett/sops"
      version = ">= 1.0"
    }
  }
}

provider "aws" {
  region = var.aws_region
}

module "core" {
  source       = "../../mantle/modules/core"
  project_name = var.project_name
  environment  = var.environment
}

module "api" {
  source      = "../../mantle/modules/api-gateway"
  name_prefix = module.core.name_prefix
  tags        = module.core.common_tags

  redeployment_trigger = sha1(join(",", [
    jsonencode(aws_api_gateway_method.device_event),
    jsonencode(aws_api_gateway_integration.device_event),
    jsonencode(aws_api_gateway_method.device_register),
    jsonencode(aws_api_gateway_integration.device_register),
    jsonencode(aws_api_gateway_method.feedly_webhook),
    jsonencode(aws_api_gateway_integration.feedly_webhook),
    jsonencode(aws_api_gateway_method.files_get),
    jsonencode(aws_api_gateway_integration.files_get),
    jsonencode(aws_api_gateway_method.files_by_id_delete),
    jsonencode(aws_api_gateway_integration.files_by_id_delete),
    jsonencode(aws_api_gateway_method.user_delete),
    jsonencode(aws_api_gateway_integration.user_delete),
    jsonencode(aws_api_gateway_method.user_login),
    jsonencode(aws_api_gateway_integration.user_login),
    jsonencode(aws_api_gateway_method.user_logout),
    jsonencode(aws_api_gateway_integration.user_logout),
    jsonencode(aws_api_gateway_method.user_refresh),
    jsonencode(aws_api_gateway_integration.user_refresh),
    jsonencode(aws_api_gateway_method.user_register),
    jsonencode(aws_api_gateway_integration.user_register),
    jsonencode(aws_api_gateway_method.user_subscribe),
    jsonencode(aws_api_gateway_integration.user_subscribe),
  ]))

  authorizer_lambda_invoke_arn = module.lambda_api_gateway_authorizer.invoke_arn
  authorizer_enabled           = true
  authorizer_ttl_seconds       = 0
}