# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# --- MigrateDSQL ---
# Runs schema migrations and applies per-Lambda permissions on every deploy.

module "lambda_migrate_dsql" {
  source = "../node_modules/@j0nathan-ll0yd/cli/modules/lambda"

  function_name      = "MigrateDSQL"
  name_prefix        = module.core.name_prefix
  source_dir         = "${path.module}/../build/lambdas/MigrateDSQL"
  assume_role_policy = module.core.lambda_assume_role_policy
  xray_policy_arn    = module.core.lambda_xray_policy_arn
  region             = module.core.region
  account_id         = module.core.account_id
  environment        = var.environment
  tags               = module.core.common_tags
  timeout            = 300
  layers             = [local.adot_layer_arn]

  environment_variables = merge(local.common_lambda_env, {
    DSQL_ENDPOINT     = module.database.cluster_endpoint
    DSQL_REGION       = module.core.region
    DSQL_ROLE_NAME    = "admin"
    METRICS_NAMESPACE = "MediaDownloader"
    AWS_ACCOUNT_ID    = module.core.account_id
    RESOURCE_PREFIX   = module.core.name_prefix
  })

  additional_policy_arns = [module.database.admin_connect_policy_arn]
}

resource "time_sleep" "wait_for_dsql" {
  depends_on      = [module.database, module.lambda_migrate_dsql]
  create_duration = "60s"
}

# --- MigrateDSQL trigger ---
# Re-invokes MigrateDSQL on every deploy where the Lambda bundle, permissions,
# or migration files have changed. The trigger hash covers all three sources,
# ensuring new migrations or code changes always propagate.
#
# This resource runs at APPLY time (not plan time), so Lambda code updates
# always happen before the invocation. If the Lambda returns FunctionError,
# the script exits 1 and Terraform reports the failure (does not mark Apply
# complete on a broken migration).
resource "terraform_data" "rerun_migration" {
  triggers_replace = sha256(join(",", concat(
    [filesha256("${path.module}/../build/lambdas/MigrateDSQL/index.mjs")],
    [filesha256("${path.module}/../permissions/permissions.sql")],
    [for f in sort(fileset("${path.module}/../build/lambdas/MigrateDSQL/migrations", "**/*")) :
    filesha256("${path.module}/../build/lambdas/MigrateDSQL/migrations/${f}")]
  )))

  provisioner "local-exec" {
    command = <<-EOT
      set -e
      RESPONSE=$(aws lambda invoke --function-name ${module.lambda_migrate_dsql.function_name} --payload '{"source":"terraform-deploy-rerun"}' --cli-binary-format raw-in-base64-out /tmp/mantle-migrate-rerun.json 2>&1)
      echo "$RESPONSE" >&2
      cat /tmp/mantle-migrate-rerun.json >&2
      echo "" >&2
      if echo "$RESPONSE" | grep -q '"FunctionError"'; then
        echo "ERROR: Lambda invocation returned FunctionError. Migration failed." >&2
        exit 1
      fi
      if grep -q '"errorType"' /tmp/mantle-migrate-rerun.json; then
        echo "ERROR: Lambda response contains runtime error. Migration failed." >&2
        exit 1
      fi
    EOT
  }

  depends_on = [time_sleep.wait_for_dsql]
}
