# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# Alarm inventory (CloudWatch alarms bill at $0.10/month beyond the first 10):
#   Mode: cost-optimized
#   Lambda per-function (Errors + Throttles, criticalFunctions only): 2 function(s) x 2 = 4
#   All-function error coverage: log-error notifier (enabled, $0)
#   DLQ depth: 5 (queue DownloadQueue, queue SendPushNotification, queue EndpointEvents, S3ObjectCreated DLQ, EventBridge DLQ)
#   API Gateway 5XX: 1
#   Total: 10 alarm-metrics -> 0 billable -> ~$0.00/month
module "observability" {
  source      = "../node_modules/@j0nathan-ll0yd/cli/modules/observability"
  name_prefix = module.core.name_prefix
  tags        = module.core.common_tags

  enable_alarms                     = true
  enable_dashboard                  = false
  enable_per_function_lambda_alarms = true

  alert_email_addresses = ["webmaster@lifegames.org"]

  lambda_function_names = [
    module.lambda_files_get.function_name,
    module.lambda_user_login.function_name,
  ]

  api_gateway_name = module.api.api_name
  sqs_dlq_names = [
    module.queue_DownloadQueue.dlq_name,
    module.queue_SendPushNotification.dlq_name,
    module.queue_EndpointEvents.dlq_name,
    module.queue_lambda_s3object_created_dlq.queue_name,
    module.eventbridge.dlq_name,
  ]
}

# Tier B log-error notifier: account-level CloudWatch Logs subscription filter delivers
# structured ERROR logs from every Lambda to the LogNotifier function, which publishes a
# de-bounced summary to the SNS alerts topic. No per-alarm cost (C145).
resource "aws_cloudwatch_log_account_policy" "log_error_notifier" {
  policy_name = "${module.core.name_prefix}-log-error-notifier"
  policy_type = "SUBSCRIPTION_FILTER_POLICY"
  policy_document = jsonencode({
    DestinationArn = module.lambda_log_notifier.function_arn
    FilterPattern  = "{ $.level = \"ERROR\" }"
    Distribution   = "Random"
  })
  # This policy applies to ALL log groups in the account. SUBSCRIPTION_FILTER_POLICY does support
  # selectionCriteria, but only as "LogGroupName NOT IN [...]" (exclusion; LIKE / positive IN are
  # rejected). We omit it deliberately: AWS automatically excludes a Lambda destination's own log
  # group from account-level subscription filters, so there is no recursion (AWS "Log recursion
  # prevention"), and the FilterPattern is the effective scope — only structured Powertools ERROR
  # logs match and are delivered. Each instance runs in a dedicated AWS account.
}

resource "aws_lambda_permission" "log_error_notifier_invoke" {
  statement_id  = "AllowCloudWatchLogsInvoke"
  action        = "lambda:InvokeFunction"
  function_name = module.lambda_log_notifier.function_name
  principal     = "logs.${module.core.region}.amazonaws.com"
}

# Framework-owned IAM: LogNotifier re-exports the framework handler, so its sns:Publish grant is
# emitted here rather than derived from instance-file import extraction (the MigrateDSQL precedent
# for well-known framework Lambdas). Scoped to the alerts topic only.
resource "aws_iam_role_policy" "log_error_notifier_publish" {
  name = "${module.core.name_prefix}-log-notifier-sns-publish"
  role = module.lambda_log_notifier.role_name
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect   = "Allow"
      Action   = "sns:Publish"
      Resource = module.observability.sns_topic_arn
    }]
  })
}
