# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# Alarm inventory (CloudWatch alarms bill at $0.10/month beyond the first 10):
#   Lambda per-function (Errors + Throttles): 20 functions x 2 = 40
#   DLQ depth: 5 (queue DownloadQueue, queue SendPushNotification, queue EndpointEvents, S3ObjectCreated DLQ, EventBridge DLQ)
#   API Gateway 5XX: 1
#   Total: 46 alarms -> 36 billable -> ~$3.60/month
module "observability" {
  source      = "../../mantle/modules/observability"
  name_prefix = module.core.name_prefix
  tags        = module.core.common_tags

  enable_alarms                     = true
  enable_dashboard                  = false
  enable_per_function_lambda_alarms = true

  alert_email_addresses = ["webmaster@lifegames.org"]

  lambda_function_names = [
    module.lambda_api_gateway_authorizer.function_name,
    module.lambda_cleanup_expired_records.function_name,
    module.lambda_dev_tools.function_name,
    module.lambda_endpoint_cleanup_helpers.function_name,
    module.lambda_migrate_dsql.function_name,
    module.lambda_prune_devices.function_name,
    module.lambda_s3object_created.function_name,
    module.lambda_send_push_notification.function_name,
    module.lambda_start_file_upload.function_name,
    module.lambda_device_event.function_name,
    module.lambda_device_register.function_name,
    module.lambda_feedly_webhook.function_name,
    module.lambda_files_get.function_name,
    module.lambda_files_by_id_delete.function_name,
    module.lambda_user_delete.function_name,
    module.lambda_user_login.function_name,
    module.lambda_user_logout.function_name,
    module.lambda_user_refresh.function_name,
    module.lambda_user_register.function_name,
    module.lambda_user_subscribe.function_name,
  ]

  api_gateway_name = module.api.api_name
  sqs_dlq_names = [
    module.queue_DownloadQueue.dlq_name,
    module.queue_SendPushNotification.dlq_name,
    module.queue_EndpointEvents.dlq_name,
    module.queue_lambda_s3object_created_dlq.queue_name,
    module.eventbridge.dlq_name,
  ]
}
