# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

output "dev_tools_function_url" {
  description = "DevTools MCP server Function URL"
  value       = module.lambda_dev_tools.function_url
}
