# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# SQS queue: EndpointEvents
module "queue_EndpointEvents" {
  source      = "../../mantle/modules/queue"
  queue_name  = "EndpointEvents"
  name_prefix = module.core.name_prefix
  tags        = module.core.common_tags
  visibility_timeout_seconds = 180
  enable_dlq_alarm           = false
}
