# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# SQS queue: lambda_s3object_created_dlq
module "queue_lambda_s3object_created_dlq" {
  source                     = "../node_modules/@j0nathan-ll0yd/cli/modules/queue"
  queue_name                 = "lambda_s3object_created_dlq"
  name_prefix                = module.core.name_prefix
  tags                       = module.core.common_tags
  visibility_timeout_seconds = 180
  enable_dlq_alarm           = false
}
