# This file is generated by Mantle CLI
# To customize, remove the first line and this file will be skipped on re-generation.

# SNS Resources

resource "aws_sns_topic" "push_notifications" {
  name = "${module.core.name_prefix}-PushNotifications"
  tags = module.core.common_tags
}

resource "aws_iam_role" "sns_logging" {
  name = "${module.core.name_prefix}-SNSLogging"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "sns.amazonaws.com"
      }
    }]
  })

  tags = module.core.common_tags
}

resource "aws_iam_role_policy" "sns_logging" {
  name = "SNSCloudWatchLogging"
  role = aws_iam_role.sns_logging.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Action = [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:PutMetricFilter",
        "logs:PutRetentionPolicy"
      ]
      Resource = "*"
    }]
  })
}

resource "aws_sns_topic" "endpoint_events" {
  name = "${module.core.name_prefix}-EndpointEvents"
  tags = module.core.common_tags
}

resource "aws_sns_platform_application" "apns" {
  name                = "${module.core.name_prefix}-MediaDownloader"
  platform            = var.environment == "production" ? "APNS" : "APNS_SANDBOX"
  platform_credential = data.sops_file.secrets.data["apns.staging.privateKey"]
  platform_principal  = data.sops_file.secrets.data["apns.staging.certificate"]

  success_feedback_role_arn    = aws_iam_role.sns_logging.arn
  failure_feedback_role_arn    = aws_iam_role.sns_logging.arn
  success_feedback_sample_rate = "100"

  event_endpoint_updated_topic_arn = aws_sns_topic.endpoint_events.arn

  depends_on = [aws_iam_role.sns_logging, aws_iam_role_policy.sns_logging]
}

locals {
  apns_platform  = var.environment == "production" ? "APNS" : "APNS_SANDBOX"
  apns_app_name  = "${module.core.name_prefix}-MediaDownloader"
  apns_log_group = "sns/${module.core.region}/${module.core.account_id}/app/${local.apns_platform}/${local.apns_app_name}"
}

resource "aws_cloudwatch_log_group" "apns_delivery_success" {
  name              = local.apns_log_group
  retention_in_days = var.log_retention_days
  tags              = module.core.common_tags
}

resource "aws_cloudwatch_log_group" "apns_delivery_failure" {
  name              = "${local.apns_log_group}/Failure"
  retention_in_days = var.log_retention_days
  tags              = module.core.common_tags
}

resource "aws_sqs_queue_policy" "endpoint_events" {
  queue_url = module.queue_EndpointEvents.queue_url

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect    = "Allow"
      Principal = { Service = "sns.amazonaws.com" }
      Action    = "sqs:SendMessage"
      Resource  = module.queue_EndpointEvents.queue_arn
      Condition = {
        ArnEquals = {
          "aws:SourceArn" = aws_sns_topic.endpoint_events.arn
        }
      }
    }]
  })
}

resource "aws_sns_topic_subscription" "endpoint_events_to_sqs" {
  topic_arn = aws_sns_topic.endpoint_events.arn
  protocol  = "sqs"
  endpoint  = module.queue_EndpointEvents.queue_arn
}
