name: Documentation

on:
  pull_request:
    branches: [main]
    paths:
      - 'docs/wiki/**/*.md'
      - '.vale.ini'
      - '.vale/**'

permissions: {}

jobs:
  vale:
    name: Lint Documentation
    runs-on: [self-hosted, linux, arm64, node]
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Verify Vale version
        run: vale --version

      - name: Vale Sync
        run: vale sync
      - name: Vale Linter
        run: vale docs/wiki/
